### ISSUE TITLE
[Feature Request] Push Notifications 

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [hyalusapp/hyalus#23]
Push notifications that tie into JS (and therefore the system) are implemented in the attached patch with a few improvements outlines below to be added at a future date: [https://imagen.click/i/08d049](https://imagen.click/i/08d049.patch)

TODO:
Reply button
Dont spam the user with pings on app start up (maybe @asineth0 can help with a sane way of doing this that wont be super slow and spammy)

**Comment by asineth0** [comment]
Working on this.

**Comment by asineth0** [comment]
Added in ad94c4ab3f122d43841e9437a04be993398ea70b. Muting functionality will come in a bit.

**Comment by gidoBOSSftw5731** [comment]
see #27
