### ISSUE TITLE
[Firefox] Wrong-sized arrows in Settings

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [hyalusapp/hyalus#4]
![image](https://user-images.githubusercontent.com/13257145/112898337-b62c5500-90ae-11eb-82a3-7f491a965513.png)

only on web, clicking them opens up the camera dropdown

also you should ask for the camera permissions when the user opens the camera selector

**Comment by asineth0** [comment]
Fixed in a179bc90127c6f766bb45d2c96fe515403e248d3.
