### ISSUE TITLE
Deleted messages do not reload automatically from the right side list of channels

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [hyalusapp/hyalus#40]
Demo clip because using words is hard (I probably reccomend watching 2x speed)

https://user-images.githubusercontent.com/13257145/113536998-f74cc980-95c6-11eb-9bdb-71de511a8e16.mov

**Comment by asineth0** [comment]
Fixed in d0315aad3ffcce19e7045dfefc99dc69dac831f1.
