### ISSUE TITLE
... is typing bar moves messages lower.

### ISSUE THREAD

**Issue by oopsie1412** [hyalusapp/hyalus#49]
When someone is typing, messages are moved lower to the point where they are touching the bar with the send button.
![image](https://user-images.githubusercontent.com/55986805/114747160-8754e680-9d1e-11eb-9c91-edb278329d7b.png)

**Comment by gidoBOSSftw5731** [comment]
Probably part of the autoscroll fixes asineth plans to work on soon, but noted.

**Comment by asineth0** [comment]
Alright, good to know. Will be tackling a proper autoscroll implementation later tonight.

**Comment by asineth0** [comment]
Fixed in 4889e00.
