### ISSUE TITLE
"You can't send messages in this channel."

### ISSUE THREAD

**Issue by glitcher32** [hyalusapp/hyalus#56]
When I click on a user I want to message, it says "You can't send messages in this channel.".

I'm either missing something or this is an issue.

**Comment by gidoBOSSftw5731** [comment]
Please send information about the client you are using (mobile, desktop, web) as well as any other relevant information (just one user? all users? can you test by messaging another account? can you try making a group chat with the person?)

Also, make sure you added that person as a friend if you want to do a 1 on 1 chat.

**Comment by glitcher32** [comment]
Both accounts were tried on web version (Firefox and Chrome) and Linux client.

But yes, they are added as a friend. I havn't tried messaging another user, but when I click on the name of the user I want to message it just says "You can't send messages in this channel." at the top area.

As of for making a group with the person, im not sure what you mean. When I press the user's name I want to message and then the 3 dots at the top right, it shows both of our usernames in a list with "Create Group" button at the top. If I click that it wants me to add a 3rd user, which I assume is for... well groups.

I assume you are simply supposed to press the Friends username and message them, but all I see is "You can't send messages in this channel.". No text box to type or anything beside the call button and 3 dots button at top right.

**Comment by gidoBOSSftw5731** [comment]
For testing purposes, try and add me (gido5731) and send me a message, I can't think of a reason as to why this is happening unless @asineth0 has an idea.

**Comment by glitcher32** [comment]
UPDATE: Somehow the account were de-friended from each other, which is what caused this issue. I simply re-added as a friend.

I remember getting the notification for "USER added".

**Comment by gidoBOSSftw5731** [comment]
Oh that's interesting and makes sense, at some point we'll probably add something more specific instead of just "You can't send messages in this channel"

**Comment by glitcher32** [comment]
Well, sounds good. Sorry to waste time if this wasn't an issue.

**Comment by asineth0** [comment]
This is only supposed to happen if it's a DM channel and you're no longer friends with the user. I'll update the message to check if it's a DM channel and if so, show a more specific message.
