### ISSUE TITLE
You can't do new lines in text messages, 

### ISSUE THREAD

**Issue by Xaglinath** [hyalusapp/hyalus#65]
If you try, it just sends it as a solid message blob

![image](https://user-images.githubusercontent.com/59151002/130329756-e7e6c071-024a-4b58-bd98-5b6232251044.png)
![image](https://user-images.githubusercontent.com/59151002/130329761-7cf6028a-d471-4603-ba72-a8f2123d57b4.png)

**Comment by asineth0** [comment]
fixed in 375a834
