### ISSUE TITLE
BUG: Message sent cuts off last word if enter not hit prior

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [hyalusapp/hyalus#71]
To replicate:
Type a message out that is multiple words, do NOT add a trailing space (or punctuation? untested) to the message
Press Enter
Observe message sent is missing the last word

Expected:
Message includes entire text field, even with no trailing space.

Tested: Chrome OS PWA, latest Hyalus deployed.

**Comment by asineth0** [comment]
Can you test this again? Seems fine now.

**Comment by gidoBOSSftw5731** [comment]
Fixed, may have been a client issue as well
